### ISSUE TITLE
There is no error triggered for duplicated value in "matches" key from manifest.json

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#1108]
**Steps to reproduce:**
Try to submit the attached web-extensions on AMO:
[pause_yt-1.0-an+fx.zip](https://github.com/mozilla/addons-linter/files/735521/pause_yt-1.0-an.fx.zip)

**Expected results:**
The webextension is not submitted and an error is displayed describing the problem.

**Actual results:**
The webextension is successfully submitted with no errors and the duplicated value is mentioned twice in permission installation doorhanger.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 54.0a1 (2017-01-27) under Windows 10 64-bit.
- Please see the attached screenshots for this issue:
![2017-01-27_1658](https://cloud.githubusercontent.com/assets/18114210/22375294/1bbeb15e-e4b2-11e6-9cc4-6a20e8f3e854.png)

![2017-01-27_1651](https://cloud.githubusercontent.com/assets/18114210/22375299/22a147ac-e4b2-11e6-8a6b-c31aea86b9d9.png)

**Comment by wagnerand** [comment]
If Firefox allows this, I don't think the linter should fail on it. We could issue a warning though :)

**Comment by andymckay** [comment]
In this cause the extension has a http and https match of the same domain. The permission prompt is because of https://bugzilla.mozilla.org/show_bug.cgi?id=1350277 and that's being fixed.

If you've two identical domains and protocols (eg: https://example.com twice) Firefox does not show you the prompt twice, throw an error or anything.

I don't think we should be doing anything there.
