### ISSUE TITLE
Auto-reject static themes

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#1213]
AMO isn't ready to support static (WebExtension) themes yet, so we need the linter to automatically reject them. We need to detect the `theme` key in the manifest, [like here](https://github.com/andymckay/webextensions-examples/blob/static-theme/static-theme/manifest.json#L9-L17), and throw an error with the following message: `WebExtension theme uploads are currently not supported.`

**Comment by EnTeQuAk** [comment]
now that I started working this I wonder if the linter is the right place for it. Especially since people are using the linter via web-ext locally too but I think warning / erroring early is probably the reason for it to belong to the linter in the first place?

I personally would implement this directly in AMO on upload unless there's good reasons for people to see the errors locally too?

**Comment by jvillalobos** [comment]
I'm okay with implementing this directly on AMO.

**Comment by EnTeQuAk** [comment]
This got merged, will be online next Thursday.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : "online" aka in -dev? or "prod"?
Checked this few minutes ago and and submission of static themes is allowed and did not find any waffle.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7) for listed and unlisted distribution.
WebExtension themes are not supported yet.
Postfix screenshot:
![listed](https://cloud.githubusercontent.com/assets/15685960/25271834/2f29d4a8-268e-11e7-8414-8d754d3ecf29.png)
