### ISSUE TITLE
linter should recognize the "identity" permission

### ISSUE THREAD

**Issue by wbamberg** [mozilla/addons-linter#1253]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1358523.

The "identity" permission is needed to use the [identity](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/identity) API. It seems that the linter does not recognize this permission, and gives a warning to add-ons that include it.

**Comment by mstriemer** [comment]
This was fixed by #1238. There was a new AMO release yesterday which included it and a new build of addons-linter with it was released on Monday (#1250).

I believe we still need to update web-ext with the latest addons-linter. I filed https://github.com/mozilla/web-ext/issues/930 to update web-ext.

From now on when Nightly moves to Beta we'll make a new addons-linter release and include that in a new web-ext release so the validation should stay up to date.
