### ISSUE TITLE
Warnings for locale-dependent CSS using predefined messages

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#1299]
### Is this a feature request or a bug?

Bug

### What is the current behavior?

After following the [guidelines for locale-dependent CSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Locale-dependent_CSS) using predefined messages (documentation for [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Predefined_messages), [Chrome](https://developer.chrome.com/extensions/i18n#overview-predefined), [Opera](https://dev.opera.com/extensions/internationalization/#predefined-messages)) for my [text to speech browser extension](https://joelpurra.com/projects/talkie/) I get warnings running `web-ext lint`.

```text
Code               Message        Description                                               File                          Line   Column
CSS_SYNTAX_ERROR   Unknown word   An error was found in the CSS file being processed as a   resources/style/options.css   64     5
                                  result further processing of that file is not possible
```

Reformatted:

```text
Code: CSS_SYNTAX_ERROR
Message: Unknown word
Description: An error was found in the CSS file being processed as a result further processing of that file is not possible
File: resources/style/options.css
Line: 64
Column: 5
```

Line 64 in `resources/style/options.css`:

```css
    margin-__MSG_@@bidi_start_edge__: 1em;
```

### What is the expected or desired behavior?

As the CSS is following guidelines, I expect to have no warnings. Similarly, I also expect no warnings when submitting the WebExtension to AMO.

### Version information (for bug reports)

node: v7.10.0 
npm: v4.2.0
web-ext: v1.9.1

Originally reported by @joelpurra in https://github.com/mozilla/web-ext/issues/951

**Comment by muffinresearch** [comment]
Do the substitutions still work in chrome/Firefox if the `@`  are escaped? Since @ has special meaning in CSS it seems an odd choice for use as part of a variable.

**Comment by EnTeQuAk** [comment]
@muffinresearch any idea who else could answer that?

**Comment by joelpurra** [comment]
@muffinresearch: when [escaping the `@` in CSS using `\0040`](https://www.w3.org/International/questions/qa-escapes#cssescapes):

- Running `web-ext lint` still gives `CSS_SYNTAX_ERROR` (web-ext v5.2.0 from 2020-10-05).
- Both Chrome v85 and Firefox v81 do not render properly, as the escaped message strings remains unprocessed (instead of being replaced by the predefined values such as `ltr`/`left`/`right` at extension load-time).

---

Regarding naming:  I didn't choose the `@@` part of the message variable name -- they're [predefined messages](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Predefined_messages). In Talkie's CSS, local-dependent strings are used to get i18n LTR/RTL support (`@@bidi_dir`, `@@bidi_start_edge`, `@@bidi_end_edge`) as documented in the guidelines.

> The i18n module provides us with some predefined messages, which we can call in the same way as we saw earlier in [Calling message strings from manifests and extension CSS](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Calling_message_strings_from_manifests_and_extension_CSS).
> [---]
> Predefined messages use exactly the same syntax, except with `@@` before the message name, for example
>
> ```
>  __MSG_@@ui_locale__
>  ```

Might be good to add some sample LTR/RTL CSS usage of predefined messages to for example [`notify-link-clicks-i18n
`](https://github.com/mdn/webextensions-examples/tree/master/notify-link-clicks-i18n), for reference and verification.

**Comment by Rob--W** [comment]
This issue was incorrectly closed, the bug report is still valid.
To reproduce, create a CSS file with the following content and run the linter:

```
body {
  margin-__MSG_@@bidi_start_edge__: 10em;
}
```


To fix this, CSS files should be preprocessed using logic similar to: Firefox: https://searchfox.org/mozilla-central/rev/919607a3610222099fbfb0113c98b77888ebcbfb/toolkit/components/extensions/ExtensionCommon.jsm#1934-2006
