### ISSUE TITLE
Validate the size of icons

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-linter#1329]
Firefox expects icons to be at least 16 pixels in size. We should require that there be at least one icon that is at least 16 pixels in size. This should check the size defined in the manifest but it would also be nice to check the size of the actual image building off of #1328.

**Comment by apoorvasingh17** [comment]
@mstriemer Hi, can I take this up?

**Comment by mstriemer** [comment]
@apoorvasingh17 You're welcome to work on this. It looks like there is a solution in https://github.com/mstriemer/addons-linter/commit/4efaf084bb7a5ec4b877856d1c135bc8d2c27ba6 that may work, but I haven't tried it in a while. It should give you an idea of how to solve this at least.

Thanks! Let me know if you require any assistance.

**Comment by asamuzaK** [comment]
@muffinresearch  I think this is already fixed in [Added check to add warning in case of corrupt image file by ravneette · Pull Request #1581 · mozilla/addons-linter](https://github.com/mozilla/addons-linter/pull/1581 "Added check to add warning in case of corrupt image file by ravneette · Pull Request #1581 · mozilla/addons-linter")

**Comment by muffinresearch** [comment]
@asamuzaK yep looks like it, thanks for the heads-up!
