### ISSUE TITLE
followup on new jest based test infrastructure

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1343]
I just merged the first part to run our tests with Jest. Lets do a few cleanups:

* test.cli-process should be some kind of integration test
* ~~use sinon sandbox similar to what addons-frontend does (https://github.com/muffinresearch/addons-frontend/blob/bdcb7858594d5c09294f468e8c733151e1a4a8e4/tests/setup.js#L64-L74)~~ - https://github.com/mozilla/addons-linter/pull/1369
* check for docs in need of an update
* https://github.com/mozilla/addons-linter/pull/1334#discussion-diff-121077807R132
* unify `.toBe` and `.toEqual` tests
* check and make sure that we don't have any tests that are needlessly `toBeTruthy` or `toBeFalsey`

**Comment by muffinresearch** [comment]
> check and make sure that we don't have any tests that are needlessly toBeTruthy or toBeFalsey

I would go as far as to suggest we avoid using those expect matchers entirely. We don't allow falsey/truthy comparisons in code via linting so I think it's best to avoid them in tests too.

**Comment by rpl** [comment]
Follows some additional notes related to the creation of a new integration testsuite for the addons-linter.

## Goals

1. integration tests on the addons-linter bin scripts:

   - a minimal set of smoke tests on the addons-linter bin script running as a whole and without any mocks, to ensure that everything is working as expected once the project sources are running using its real npm dependencies
   - test on the cli interface (e.g. porting the test.cli-process from the unit tests to the integration tests)
   - test the firefox-schema-import script
   - test the build-locales / create-locales / merge-locales scripts
   
2. running the addons-linter on some real extension:

   - run the addons-linter on a small set of real extensions submitted on AMO and/or on some of the example extensions from the mnd/webextensions-examples repo, to ensure that the addons-linter behavior is consistent across its new releases (and catch some of the new potential regressions that can be introduced as a side-effect of adding new rules to the addons-linter)
   
## Implementation notes

- the new integration test suite can still make use of jest as the test runner and use its test assertions
  - Link to some existent projects which uses jest in its integration tests:
    - The jest project itself uses jest to run its integration test suite: https://github.com/facebook/jest/blob/23eec748db0de7b6b5fcda28cc51c48ddae16545/integration-tests/__tests__/cli-handles-exact-filenames.test.js#L24-L41      
    - I also used jest for the integration tests on flow-coverage-report: https://github.com/rpl/flow-coverage-report/blob/cda474738aa4ec53138c577dc285d6d3ffbbbdf7/__tests__/integrations/cli/test-issue-135.js#L14-L22
    
- the integration tests are going to read and write to real files, and so every test case should run in its own temporary directory (which should have a generated unique name and be automatically removed once the test or the test suite run completes)
  - follows some links to existent projects that uses an helper to create "auto-destroyed temporary directory" for its tests that access real files:
    - web-ext defines a `withTempDir` helper on top of the "tmp" npm package:
      https://github.com/mozilla/web-ext/blob/18b724310841183c83558acc9d713a51f7671b21/src/util/temp-dir.js#L25-L33
    - then it wraps the test cases that access real files using the `withTempDir` helper:
      https://github.com/mozilla/web-ext/blob/dbdf9e24598cf2879f817f8a2245c9e860d57977/tests/unit/test-util/test.is-directory.js#L30-L39
  
- the integration tests should provide a shared test helper to execute one of the addons-linter bin scripts and collect its: exit value, stdout and stderr
  so that we can makes assertions on the execution results and/or use the jest snapshots to ensure that the results are consistent across the addons-linter releases (the jest and flow-coverage-report integration tests linked above contains used of both these approaches)

- it could be helpful if we could split the integration test suite from the unit test suite in a different travis and appveyor job

- we should evaluate if we should cache external resources (e.g. the extensions to test and maybe the last downloaded tar.gz for the firefox-schema-importer) on travis/appveyor (and define/document how/when we should invalidate the cache)
