### ISSUE TITLE
Add a switch to easily disable/enable existing rules

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#1436]
In order to mitigate the risk when having more and more complicated rules, it'd be good to have a system to dynamically enable and disable existing rules without having to wait for a push.

@EnTeQuAk said it should be fairly straightforward 😊

I assume this needs a counterpart on *addons-server* for a UI?

**Comment by EnTeQuAk** [comment]
> I assume this needs a counterpart on addons-server for a UI?

Indeed it does.

**Comment by Anshika-G** [comment]
@wagnerand can you pls elaborate?

**Comment by EnTeQuAk** [comment]
A bit more information:

We have a list of rules that inherits from eslint which are used to lint Add-ons. This issue is about adding an argument that takes a list of rules that can be disabled, for example if we notice that many add-ons submitted to addons.mozilla.org (where the linter is used) run into problems with newly added rules.

You can find the arguments the command line defines in https://github.com/mozilla/addons-linter/blob/master/src/cli.js#L27-L83

and the list of rules are applied to eslint in https://github.com/mozilla/addons-linter/blob/master/src/scanners/javascript.js#L58 and in https://github.com/mozilla/addons-linter/blob/master/src/scanners/javascript.js#L73-L75

So at the best that command line argument should take a list of comma separated rule-names which are then excluded and not forwarded to eslint.

Please let me know if you have any questions or run into any problems!

**Comment by hameleonka** [comment]
I can take it

**Comment by EnTeQuAk** [comment]
@hameleonka absolutely! Let me know if you're working on this so I can set the appropriate label and also let me know if you run into any problems / questions.

**Comment by hameleonka** [comment]
@EnTeQuAk , yes I'm working on this problem. Also could you please check your mozilla email? I've sent you an email with questions about Outreachy program (from Natalia Milovanova hameleonka28@gmail.com). Thanks.

**Comment by wagnerand** [comment]
@hameleonka, @EnTeQuAk will be back in a few days, sorry for the delay.
