### ISSUE TITLE
Firefox for Android support

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#1564]
We know what API works in Desktop and what works in Android - generally speaking its the difference between the API existing in `browser` or `toolkit`. It would be nice to be able to target the linting to a specific application. i.e.: if i lint for Android, it should throw a warning saying nativeMessaging doesn't work there.

This is a big bug that could lead to some neat goals: being able to tell if an extension works on other browsers, being able to automatically detect platform support in AMO.

**Comment by EnTeQuAk** [comment]
That'd be nice indeed. Sounds like quite a lot of restructuring of the import process to me though, afaik the schemas get's merged together so that we have the broad picture imported. The information from where a schema file comes can probably be piped through and put on the appropriate APIs in the schema files. cc @mstriemer on this though since I only know so much of the schema import process.

**Comment by EnTeQuAk** [comment]
This has actually been tackled as much as possible by fc1ddbcb363b3a603513eca63b5f5f8498be1ee0
