### ISSUE TITLE
Support Static Themes in the linter

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-linter#1587]
See mozilla/addons/issues/501 and connected issues for background.
We need the linter to know about Static Themes.  There are a few mandatory fields:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme

As just having `theme:` in your manifest makes it suddenly not an extension but a theme we might want to warn about having other stuff in the manifest/zip that is now ignored too.

**Comment by AlexandraMoga** [comment]
@eviljeff @EnTeQuAk  Could you please provide more details with regards to what should be expected now when validating a static theme? Are there any errors/warnings to be detected depending on specific conditions?

**Comment by EnTeQuAk** [comment]
QA: the linter verifies only the `manifest.json` of a theme so to test this:

* Make sure your `manifest.json` has a `theme` property, once it does the linter detects that this add-on is a theme and starts linting it's properties
* Outside the `theme` property, on the root of the `manifest.json` it only supports these properties: https://github.com/mozilla/addons-linter/blob/master/src/schema/imported/manifest.json#L10-L74 (so `manifest_version`, `applications`, `name`, `short_name` etc) and **errors** on any additional property. IN addition to the base manifest properties it supports the `icons` property too.
 * You can look at https://github.com/mozilla/addons-linter/blob/master/src/schema/imported/theme.json#L145-L489 for specific properties that are supported, as an example you could make sure that `additional_backgrounds_alignment` (inside `theme`) only supports `"bottom", "center", "left", "right", "top", "center bottom", "center center", "center top", "left bottom", "left center", "left top", "right bottom", "right center", "right top"` as values or colors correctly behave how `ThemeColor` is defined (ThemeColor, which is defined https://github.com/mozilla/addons-linter/blob/master/src/schema/imported/theme.json#L118-L141 and means it can be any string, or an array with exactly 3 items (rgb) or an array with exactly 4 items (rgba) but nothing else. So a simple number, e.g `"accentcolor": 4` should not work)

I think that's mostly it, always take results with a grain of salt since all validation is taken directly from the schema but the scenarios I mentioned should be verifable. Let me know if you have any questions!

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59, Win10x64

Some criteria mentioned above are behaving as expected but I've also found some (possible) issues.
I will mention here the things that work and I will open a new issue to track the aspects that need to be clarified.

What works:
- errors are detected if the root of the manifest contains the following properties: `langpack_id`  content_script,  `permissions`
- additional_backgrounds_alignment - only accepts the properties defined [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme#properties) 

Opened #1913 for the issues that need to be clarified.
