### ISSUE TITLE
applications.gecko.update_url error could suggest --self-hosted

### ISSUE THREAD

**Issue by KwanEsq** [mozilla/addons-linter#1614]
There was an add-on dev in #webextensions yesterday who was alarmed by the error, since they didn't want to submit to AMO.  Since not everyone will necessarily run --help before hand, the error could suggest what's needed.
Currently have a patch that adds the following sentence to the warning:
`Lint with the "--self-hosted" argument if you are hosting the add-on yourself.`
Feel free to suggest improvements/adjustments to the wording (I had "distributing" instead of "hosting" before, and it could use "elsewhere" instead of "yourself")

**Comment by EnTeQuAk** [comment]
Thanks for the report. True, the error message could be improved. The problem here is that this exact message is displayed on AMO too if someone submits their add-on into the wrong channel. We currently don't have a way for the linter to see if it runs via AMO or locally and adjust messages accordingly.
