### ISSUE TITLE
linter doesn't throw an error when content_scripts referenced from code are missing

### ISSUE THREAD

**Issue by hameleonka** [mozilla/addons-linter#1640]
### Describe the problem and steps to reproduce it:
there are 2 ways to introduce content scripts to addon
1) declaration in manifest.json covered in #1630 
2) programmatically with tabs.executeScript()

### What happened?
linter doesn't trow an error in the second case if script is missing

### What did you expect to happen?
I would expect error notification

### Anything else we should know?
(Please include screenshots and any relevant files.)
wondering how to deal with this if there is dynamic file name i.e. instead of path there could be something like `/content_scripts/${conditionalFileName}`

**Comment by hameleonka** [comment]
will work on this

**Comment by rpl** [comment]
> wondering how to deal with this if there is dynamic file name i.e. instead of path there could be something like /content_scripts/${conditionalFileName}

@hameleonka very good question!

In my opinion it could make sense to:
- raise an error if the file url specific is a "static" file url and it does not exist in the extension
- we should also raise an error if the file value is a static string and it is not an extension url
  (because it will raise a validation error when tabs.executeScript runs, the file attribute is
  validated at runtime and it allows only extension urls: https://searchfox.org/mozilla-central/rev/550148ab69b2879bfb82ffa698720ede1fa626f2/toolkit/components/extensions/ext-tabs-base.js#605-607)
- raise a non blocking warning for dynamic file names (so that it is allowed but at the same time makes the addon developers, and the reviewers, aware that a missing filename at runtime could lead to extension errors at runtime).

There are also [tabs.insertCSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS) and [tabs.removeCSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/removeCSS) that may also use this kind of validation (they are like tabs.executeScript but for the content script stylesheets), as well as [extension.getURL](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extension/getURL) which is a function that converts a relative path to a resource packaged inside the extension into an absolute extension url.

@EnTeQuAk @wagnerand how that sounds to you?

**Comment by rpl** [comment]
@hameleonka @EnTeQuAk @wagnerand another error scenario that we should take into account (also when validating that a content scripts file specified in the manifest really exists) is that when an extension is loaded from a directory (by installing the addon temporarily from "about:debugging#addons") an extension file with the wrong case can be loaded correctly on a "case insensitive" filesystem (e.g. like on OSX), but when the extension is packaged into an XPI (a zip file) the extension url in the wrong case will not be loaded (because the file names are case sensitive when loaded from an XPI on all the platforms).

I think that it would be great if the addons-linter could catch this issue.

**Comment by wagnerand** [comment]
I don't have very strong feelings about this issue, but to it sound a bit too low-level. I see that this could be useful but we have to be careful about throwing warnings because we've in the past we experienced that developers stop reading warnings if there are too many.

That being said, I am ok with raising an error if a file referenced by a static file is missing (be careful of false-positives or loopholes, as this prevents submission to AMO), but let's not raise warnings for non-static strings referencing filenames.
