### ISSUE TITLE
Show warning if add-on uses 'coinhive'

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#1643]
Including coin miners in add-ons is strictly forbidden, and [Coinhive](https://coinhive.com/) is the method most often used by developers for this. We need to look for the string 'coinhive' in add-on code and show an error if present. It can lead to some false positives, but they should be rare and easy to work around.

Error message: `Firefox add-ons are not allowed to run coin miners.`

**Comment by wagnerand** [comment]
Note that most ad blocker filter lists include the string 'coinhive'. We don't want to deny those.

**Comment by jvillalobos** [comment]
One possible alternative would be to check for `CoinHive` with strict casing, so it catches the object used in the library. It wouldn't work for add-ons loading it remotely, though.

**Comment by jvillalobos** [comment]
Switching to a warning so we can move forward with this. We can be more strict in this case without worrying about false positives. Calling this a P2 since it's becoming much more common.

**Comment by EnTeQuAk** [comment]
I'm working on this right now, I was wondering if we might want to reuse the blacklist from https://github.com/keraf/NoCoin which might be a bit more useful than simple string blacklisting? I'll try both attempts and see what gives better results.

**Comment by EnTeQuAk** [comment]
That's perfect, thanks! We will add more filters over time once we notice more coin mining software being uploaded in different ways but that'll work fine for now.

**Comment by vcarciu** [comment]
Thanks @EnTeQuAk !
Marking bug as verified.

**Comment by ParticleCore** [comment]
I don't know if it is of any use, but I forgot to remove the opt-in mining section from the code while testing an unlisted version and AMO correctly warned as described here.  

However, I only found this out because I clicked the full validation report and not before because this warning is only showing in the full report.  

I would suggest that this warning were to be displayed in the prior screen as well for a more immediate awareness.
