### ISSUE TITLE
Make a disallowed `Identifier` util

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#180]
We're doing similar things in the BANNED_IDENTIFER checks as mozIndexedDb checks we could have a utils to dry up this logic.

**Comment by tofumatt** [comment]
44.3 is done and this is an improvement but I'm taking it off the iteration labels for now.

**Comment by johannhof** [comment]
I'll take care of this, we can probably move `mozIndexedDb` into the BANNED_IDENTIFIERs

**Comment by johannhof** [comment]
@muffinresearch @tofumatt https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#regex-tests says that use of mozIndexedDb is supposed to trigger a warning. The validator currently treats it as an error, though. What's the correct behaviour?

**Comment by tofumatt** [comment]
I changed it from a warning to an error.

It's a very outdated API and I think we should now treat it as an error; any add-on using the old code should upgrade.

- tofumatt (Sent from mobile)

**Comment by johannhof** [comment]
Ok, that means we can't just add it to `BANNED_IDENTIFIER` :neutral_face:

As I see it we have two possibilities here:

We can go the easy route and just simplify the `mozIndexedDb` to read exactly like the `BANNED_IDENTIFIER`s code but with an error.

__Or__ we could instead add another sort of `BANNED_IDENTIFIER`s, maybe call them `BANNED_IDENTIFIER_ERROR` or `FORBIDDEN_IDENTIFIER` or something. The only entry in the list would be `mozIndexedDb` for now, but we could easily extend it whenever we need an identifier that causes an error.

It would be roughly the same amount of code for both, so I'd choose the latter alternative since it sounds more scalable. :frog:

**Comment by tofumatt** [comment]
Agreed, the latter is better. 👍

Turning `BANNED_IDENTIFIERS` into an object where the keys are the identifiers and the values are the warning level is even cleaner.

**Comment by johannhof** [comment]
Good idea!

**Comment by kmaglione** [comment]
@johannhof Are you still working on this, or should we open it for someone else?

**Comment by johannhof** [comment]
@kmaglione Oh, I suppose I never got around to finish this after all, sorry, please do reassign.

**Comment by atsay** [comment]
@EnTeQuAk is this issue still relevant?

**Comment by EnTeQuAk** [comment]
I'm closing this for now, this is relevant but the related code will go away very soon so it won't make sense to change / fix it. Once this will be reimplemented with WebExtensions in mind we will try to keep everything here in the comments in mind.
