### ISSUE TITLE
Remove fucked, fuck, queer from badwords

### ISSUE THREAD

**Issue by lgierth** [mozilla/addons-linter#1851]
### Describe the problem and steps to reproduce it:
1. (to) fuck up is in regular colloquial use around the world -- https://en.wiktionary.org/wiki/fuck_up
2. How queer ended up on that list is a mystery to me. There's no good reason at all really.

### Anything else we should know?
(Please include screenshots and any relevant files.)

**Comment by wagnerand** [comment]
@jvillalobos @caitmuenster

**Comment by jvillalobos** [comment]
That list is meant to block submission of add-ons that violate our [Acceptable Use policy](https://www.mozilla.org/en-US/about/legal/acceptable-use/). While there may be valid uses for those words, more often than not they are used in ways that are not allowed for listed AMO add-ons. Since it looks like you just need to make changes to a couple of comments on your end, I don't think we need to make any changes here.

**Comment by VictorBjelkholm** [comment]
@jvillalobos the badwords that are mentioned in the issue, which rule do they fall under exactly? I'm failing to understand how the usage of "fuck" is blocked by any of the rules listed in the "Acceptable Use Policy" you linked.

**Comment by jvillalobos** [comment]
> Degrades, intimidates, incites violence against, or encourages prejudicial action against someone or a group based on age, gender, race, ethnicity, national origin, religion, sexual orientation, disability, religion, geographic location or other protected category or constitutes hate speech

Context matters, of course, but the use of such words (and similar ones) for those purposes is the reason the list was introduced.
