### ISSUE TITLE
Mark GA use in Permission Information Pop-up

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1947]
I am not sure if liner is responsible for the data on "Request the right permissions" or not.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Request_the_right_permissions

I have been discussing the review aspect of the issue with Andreas & Philipp.

However, from users point of view, a notification should be greatly beneficial.

Numerous add-ons now use GA in their add-on to collect some sort of data and pass to Google which will then be used for the data-mining and marketing as stated by the Google.

The inclusion of GA tracking is often not enclosed by the developers thus users are unaware of such data collection and it is done without user-consent.

I propose a (controversial!) new entry in the Permission Information Pop-up for any add-on that is using "google-analytics.com" in order to inform users of the existence of trackers and their consequence for their privacy.

Looking forward to feedback on the proposal from all.

![Permission Pop-up](https://mdn.mozillademos.org/files/15736/General_permissions_message_example.png)

**Comment by jvillalobos** [comment]
There's a plan underway to support certain privacy flags in the add-on manifest, which would be exposed by AMO and possibly Firefox, which sounds like this, pretty much. There's some info about it [here](https://trello.com/c/yvvCmDA6/12-privacy-flags-on-amo).

It's not a high priority right now, so I can't give any assurances as to when we will have it. Closing this issue since we're tracking this elsewhere.
