### ISSUE TITLE
False positive: “Violation of Mozilla conditions of use”

### ISSUE THREAD

**Issue by fnxweb** [mozilla/addons-linter#1952]
### Describe the problem and steps to reproduce it:
Every time I upload one of my extensions, I get an info. report of a “Violation of Mozilla conditions of use” within the Hungarian help HTML file inside it.

I haven’t a clue what it doesn’t like; I didn’t do the translation myself, but Google Translate doesn’t show anything untoward. I suspect the analysis doesn’t know it’s not English?

It was suggested on the developer discourse channel that I report it here.

### Anything else we should know?
The offending HTML file:  https://github.com/fnxweb/urllink/blob/master/release/_locales/hu_HU/help.html

**Comment by fnxweb** [comment]
Most of the help files have anal in some fashion, so to speak, but only the Hungarian one complains.

**Comment by welwood08** [comment]
In all of the other instances, the next character is ASCII. In this case, it is not - hence my untested theory of a word boundary occurring and causing this instance to match the bad word.

Since the ecma-international.org link in the code comment seems to be down, I'll refer to https://es5.github.io/#x15.10.2.6 which appears to be about RegExp. The algorithm for `\b` calls "IsWordChar" which has a very restricted set of characters, all within the ASCII range. Obviously the badwords code needs to be taught how to deal with this properly, but in the mean time it'd probably be quicker to find an alternative word for that language.

**Comment by fnxweb** [comment]
OK, I've come up with a hacky work-around;  you were right, it was that word.

I've just made use of the Unicode zero-width joiner `&zwj;` — plonking that in the middle of the “offending” word has cleared up the report, and still shows up OK in the browser: `an&zwj;alízis`

**Comment by poelon** [comment]
quite similar, retard is flagged as bad word but in French retard means delay!

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/addons-linter/issues/2591.
