### ISSUE TITLE
Use babel-eslint parser instead of espree

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2076]
We should be using https://github.com/babel/babel-eslint instead of espree. There are various reasons for that.

1) `babel-eslint` supports an `allowImportExportEverywhere` option, it also set's the `sourceType` to `module` by default
2) This wouldn't be needed if https://github.com/eslint/espree/issues/334 got implemented, I don't see this happening anytime soon

This may simplify future adaption of new syntax since babel probably will always be faster and more up-to-date than espree/eslint.

**Comment by muffinresearch** [comment]
Are we wanting to do this because setting the correct module sourceType is proving difficult. I'd like to understand the thinking here a bit more.

I'm not sure why we'd be in a position where the syntax used in extensions is so far ahead of where eslint is at, after all eslint needs to keep up with browser support. Are there other examples of needing to do this aside from module related code?

I'd be a bit concerned about adding something that monkey patches eslint so that code is transformed, if we can avoid doing that we should.
