### ISSUE TITLE
Create changelog of what changed in addons-linter

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2133]
@rpl mentioned this and it's a great idea. Let's create a ChangeLog file that follows what changes in the addons-linter.

Could be part of our #2059 (addons-linter docs refactoring)

**Comment by obviyus** [comment]
Can I work on this? Where do we want to store the changelog file?

**Comment by rpl** [comment]
@EnTeQuAk in the web-ext repository we do use [commitlint](https://commitlint.js.org/#/) to automate a good chunk of the work needed to generate a changelog on every new release, we are using this approach for a long time now and it works great if the commitlint conventions are enforced on the commit messages.

e.g. for web-ext project we are describing the commitlint conventions here: 
- https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages

we are also enforcing the commit conventions by linting the commit message (or the pull request title if the pull request includes more than one commit, because the pull request title becomes the commit message if the pull request is squashed and merged):

https://github.com/mozilla/web-ext/blob/9735a1f48696cd2dce719688fc4ce9f7cb3883f2/.travis.yml#L27

If that approach sounds good to you too, I'll be happy to provide more details about the approach we use in the web-ext repo to make it easier for a contributor to work on this.

Let me know how that sounds to you.

**Comment by rpl** [comment]
Closing for now, we may re-evaluate later on.

**Comment by willdurand** [comment]
> Closing for now, we may re-evaluate later on.

note that I write GitHub releases with notable changes (that aren't just git logs)

**Comment by rpl** [comment]
@willdurand Yep, on web-ext I do actually do pretty much the same, but I use the generated "conventional changelog" derived from the commit message as the base for some more manual editing.

Some additional context:
we filed this quite some time ago because some of the linter releases were actually missing a changelog from time to time, but at the moment I'm actually pretty happy with the changelog you are writing down (and I tell this as a "user" of that changelog, I use it to detail the changes related to the `web-ext lint` comment in the `web-ext` changelog) and so during the "good first bugs triage meeting" we agreed to close this "contrib: welcome" bug.
