### ISSUE TITLE
Warn on nested zip files

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2223]
Following https://github.com/mozilla/addons-server/pull/9584/ the linter should warn for nested ZIP files, originally we expanded `.crx`, `.jar`, `.xpi`, `.zip` files but in theory the same problems with zip files apply with tar files and more.

We should rather warn about them or even disallow them altogether.

Originally nested .zip/.jar files were used to distribute additional software together with an add-ons XPI file, that is not needed anymore with WebExtensions.

**Comment by wagnerand** [comment]
In the legacy world, .jar files were used to package some of the files in order to speed up loading the extension.

I will run a code search to see if we have any signed webextensions are doing that. My assumption would be 'no'.

If anything, I think it would be ok to raise a warning if we find a .zip or .jar file, as those seem to have the highest chance of ever being used.

I don't think we should put in a lot of effort here, since the chances of that happening should be rather low, given that it requires a JavaScript implementation of the compression algorithm. As far as I know, one exists for .zip.

**Comment by wagnerand** [comment]
I searched for .zip and .jar files and found none.

**Comment by wagnerand** [comment]
Fine with me!

**Comment by suhailsinghbains** [comment]
Hi, Is this bug free to work on? Would love to work on this.
Thanks

**Comment by muffinresearch** [comment]
@suhailsinghbains please feel free to work on it if you are still able to.

**Comment by eviljeff** [comment]
removing @suhailsinghbains as it's inactive for a long time.

**Comment by willdurand** [comment]
We decided to close this issue because we treat zip files like any other binary files.
