### ISSUE TITLE
Stop .xpis with unsupported image types from being submitted 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-linter#2243]
Related to #[9667](https://github.com/mozilla/addons-server/issues/9667#issuecomment-429937981) on the addons-server repo. 

Let's stop .xpis with [unsupported image file types](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme) from being submitted to AMO. 

The linter should return a message saying that the file type is not supported.

**Comment by asamuzaK** [comment]
It warns (at least).
https://github.com/mozilla/addons-linter/blob/master/src/parsers/manifestjson.js#L380
https://github.com/mozilla/addons-linter/blob/master/src/const.js#L103

**Comment by EnTeQuAk** [comment]
There is already validation for the `icons` property happening in `src/parsers/manifestjson.js` -> `validateIcon` which also validates the images by actually opening the first part of them and reading their size.

So that functionality can be re-used for this purpose. See `validateIcons` for a bit more information on this, all that should be generalized into a `validateImage` function that has the ability to check arbitrary sizes (for icons) as well.

**Comment by eviljeff** [comment]
yeah, duping this to #2501
