### ISSUE TITLE
"homepage_url"s pointing to AMO websites should be restricted during validation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#2253]
Follow up for https://github.com/mozilla/addons-server/issues/9012

STR:
1. Log in to AMO dev
2. Create a new extension and add a `"homepage_url"` property pointing to addons-dev.allizom.org
3. Submit your add-on

Actual result:
Add-on passes validation without any errors

Expected result:
Homepage URLs pointing to AMO websites should trigger an error during validation to comply with the current implementation in Dev Hub

Notes:
- reproduced on AMO dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/47355321-be0b9200-d6c9-11e8-8c5a-f5414f671318.png)

**Comment by rbrishabh** [comment]
Hey! I would like to tackle this!

**Comment by ThamiMemel** [comment]
i would like to work on this issue

**Comment by ThamiMemel** [comment]
Here's a first draft, most likely subject to multiples changes.
Here are some point probably need to be edited . hopefully someone with more insight into the project can guide me.

- **Restricted domain should be inside some sort of config file ?** 

- **Error code and description could be better ?**

- **Should i make a test case for this ?**

**Comment by rpl** [comment]
> Here's a first draft, most likely subject to multiples changes.
> Here are some point probably need to be edited . hopefully someone with more insight into the project can guide me.
> 
>     * **Restricted domain should be inside some sort of config file ?** 
>     * **Cureently the checking is a simple indexOf maybe a regex is better ?**

It depends from what degree of flexibility this validation rule should have.
e.g. addons-dev.allizom.org is a non production instance of the demo portal, but based on the original issue linked to this one it seems that addons.mozilla.org is the main domain that we were meant to disallow.
But, are those the only urls that we want to disallow? (e.g. should we also disallow localhost?).

@Yrkan this issue has been stale for a while, let's double-check that is still valid and what kind of behavior we did want the implement on the linter side.

> 
>     * **Error code and description could be better ?**

New error codes does also need to be added to docs/rules.md, and there is a test that does cover that and it is currently failing in the draft patch in #3415 (See https://travis-ci.org/github/mozilla/addons-linter/jobs/738802933#L478)


>     * **Should i make a test case for this ?**

yes, any rule should be covered by explicit test cases, to make sure that the expected behaviors are implemented and that they do not regress.

But let's double-check first that this issue is still valid, and (if it is) what are the behaviors that the new rules should implement.

**Comment by rpl** [comment]
@willdurand is this still something that we still want to do also on the addons-linter side? or is it already covered by (or should be covered by more) by server side checks?

If this issue is still valid, we should agree on what are the expected behaviors that we should implement (e.g. disallow addons.mozilla.org, addons-dev.allizom.org and localhost? maybe but just include an array of disallowed domains in a const bundled with the linter itself).

**Comment by willdurand** [comment]
> @willdurand is this still something that we still want to do also on the addons-linter side? or is it already covered by (or should be covered by more) by server side checks?

I think so? I mean, it is definitely implemented on AMO (cf. https://github.com/mozilla/addons-server/pull/9722)

**Comment by rpl** [comment]
Closed by #3415
