### ISSUE TITLE
Add-On Validation fails, even when there are no warnings or errors

### ISSUE THREAD

**Issue by EdwardCaulfield** [mozilla/addons-linter#2376]
### Describe the problem and steps to reproduce it:

I am attempting to update an existing FireFox Add-On by uploading a new ZIP file and I am being informed "<em:type> in Ihrer install.rdf (1) stimmt nicht mit der ID Ihres Add-ons auf AMO (10) überein".  Roughly translated this means that the <em:type> in my install.rdf file doesn't match the ID on the Add-On.

There are several problems with this message:
0) There was no original Add-On file.  The system accepted and published the Add-On even though I never uploaded an original file. (okay - this is separate issue, but maybe it influences this issue)
1) I don't have an install.rdf in the ZIP file.
2) From what I am reading the install.rdf is a deprecated facility
3) The review results linked to in the error message show that everything passed without any issue
4) The Add-On passes addons-linter without any errors:

$ addons-linter Archive.zip 
Validation Summary:

errors          0              
notices         0              
warnings        0              

This is reliably reproduced by uploading the ZIP file listed at the bottom of this case.

### What happened?

<em:type> in Ihrer install.rdf (1) stimmt nicht mit der ID Ihres Add-ons auf AMO (10) überein 

### What did you expect to happen?

The validation would pass and the Add-On would be accepted

### Anything else we should know?

(Please include screenshots and any relevant files.)

![image](https://user-images.githubusercontent.com/2613598/51443371-23cae280-1ce8-11e9-845c-ea04435d30b4.png)
![image](https://user-images.githubusercontent.com/2613598/51443377-33e2c200-1ce8-11e9-971a-6dd146285851.png)
![image](https://user-images.githubusercontent.com/2613598/51443382-3f35ed80-1ce8-11e9-9303-dcb05cc8556e.png)
![image](https://user-images.githubusercontent.com/2613598/51443386-478e2880-1ce8-11e9-87bd-77f8106fba04.png)

[Archive.zip](https://github.com/mozilla/addons-linter/files/2776916/Archive.zip)

**Comment by wagnerand** [comment]
Thanks for filing this report. Please see the responses inline below.



> 0) There was no original Add-On file. The system accepted and published the Add-On even though I never uploaded an original file. (okay - this is separate issue, but maybe it influences this issue)

I am not sure what you mean by "original file". However, technically, this error is correct. In fact, there is already another add-on with the ID specified in your manifest.json (*{6df06f37-3d37-4b59-bd5e-5b03d74bc9ad}*) which is not an extension, but a theme. Thus, the type does not match.

>     1. I don't have an install.rdf in the ZIP file.

The file you attached to this issue does contain an install.rdf file. The data in there is mostly invalid. I won't go into details here since you need to remove that file anyway.

> 
>     2. From what I am reading the install.rdf is a deprecated facility

That is correct and another issue here. In an ideal world, ff we find an install.rdf file, we should probably fail early and raise an error that legacy add-ons are no longer supported. Unfortunately, we still have to support install.rdf for a few exceptional cases until the end of life for Firefox 60 ESR. 

> 
>     3. The review results linked to in the error message show that everything passed without any issue

Yes, AMO is a complex system so not everything can be done inside the addons-linter. This particular check runs inside addons-server, but the validation report shows linter issues only.

> 
>     4. The Add-On passes addons-linter without any errors:

addons-linter only supports webextensions and does not know anything about legacy add-ons. Thus, it does not catch that issue.

---

So, what you would want to do is remove the install.rdf file and change the add-on ID in manifest.json to something that is not used. Afterwards, please try uploading again.

**Comment by EdwardCaulfield** [comment]
Thank you very much for getting back to me so quickly on this topic.  My apologies for including the install.rdf file.  I had experimented with adding it as a result of the error message and thought that I had deleted it for the final report.  

Even after the removal of the install.rdf file from the Zip file, I am getting the same error message:
![image](https://user-images.githubusercontent.com/2613598/51471756-deee8c80-1d77-11e9-95c4-ebe59aa9a9d1.png)

Although I am not finding a source that states it clearly, I understand the the gecko:id should be the UUID for the Add-On. The UUID I am using is coming from the following:
![image](https://user-images.githubusercontent.com/2613598/51471616-88814e00-1d77-11e9-988b-27f9205cbb09.png)

If this is the theme UUID, where do I find the UUID for the Add-On?

If I change the gecko:id to any other value than the UUID (even when I use a substring of the UUID) I get:
![image](https://user-images.githubusercontent.com/2613598/51472418-ba93af80-1d79-11e9-9e32-b9e2954e88b9.png)

thus, I am confused by the statement of "change the add-on ID in manifest.json to something that is not used". I even tried removing the curly brackets around the UUID and that generates the same error as well.

The updated zip file is:
[Archive.zip](https://github.com/mozilla/addons-linter/files/2778774/Archive.zip)

Sorry of the answer to my issue is clearly documented somewhere.  I have searched high and low without hitting upon an answer.

**Comment by wagnerand** [comment]
Can you give me the link your add-on that you took the second screenshot from, please?

**Comment by wagnerand** [comment]
It seems you are trying to submit an extension with the same add-on ID as an existing theme.

Note that the add-on ID must be unique for each add-on. It is not a common ID shared among all add-ons.

Also, you cannot submit an extension as a new version of an existing theme. You have to submit it as an entirely new add-on.

**Comment by EdwardCaulfield** [comment]
Thank you for your continued assistance.  I found my mistake and it appears that I was operating under the influence of a massive cloud of stupid... It was the theme I was working under, not the Add-On itself. Sorry to have bothered you with this.

**Comment by wagnerand** [comment]
No worries, I'm glad we sorted it out!
