### ISSUE TITLE
rule: disallowed_file_type

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#275]
From https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L49

Looks for native files (JAR, etc.) and warns against their usage: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L49

**Comment by EnTeQuAk** [comment]
This is still relevant, we need a proper disallowed-files system to avoid people packaging up crap inside their zips.

**Comment by andymckay** [comment]
Hmm I got a lot of this here: https://github.com/mozilla/addons-linter/blob/master/src/const.js#L123-L142 which is from #638

**Comment by EnTeQuAk** [comment]
heh, that's true, sorry I didn't see this. I'm guessing this catches quite a lot of stuff already, it doesn't catch .jar files - not sure if we should though.

**Comment by andymckay** [comment]
If I read that code in addons-validator it looks to see if there are more than 10 files that have the .class extension here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L96-L105 and then calls it a jar. It doesn't detect for jar files through its magic numbers (because its just a zip).

The linter just flags any add-on with a .class file anywhere in it. 

A simple addition would be to add in .jar as well into the flagged files.

**Comment by andymckay** [comment]
We've got .jar, should we close this now @EnTeQuAk?
