### ISSUE TITLE
rule: missing_install_rdf

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#280]
From https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Check for an `install.rdf`, see: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L180

**Comment by EnTeQuAk** [comment]
We don't care anymore about `install.rdf` in `addons-linter` but should only do webextension stuff. yeay!

**Comment by muffinresearch** [comment]
> We don't care anymore about install.rdf in addons-linter but should only do webextension stuff. yeay!

Actually that's not necessarily true depending on what we're planning re: dictionaries and langpacks long term since they still use install.rdf and as far as I know there's not yet plans to migrate them to use a web-ext style wrapper although that could eventually be the approach taken.

We should think about this and possibly take the decision to not keep any legacy support in the linter but that decision hasn't been made yet.

**Comment by muffinresearch** [comment]
Actually based on https://github.com/mozilla/addons-linter/issues/1063 I think we can make this decision now to go ahead and make this the direction. If we want to add back support for install.rdfs we can do so later on.
