### ISSUE TITLE
Error A background script defined in the manifest could not be found

### ISSUE THREAD

**Issue by vrgomes** [mozilla/addons-linter#2814]
### Describe the problem and steps to reproduce it:

Hi I have uploaded a new Addon and it gives this error:
![Screenshot Capture - 2019-09-27 - 14-58-56](https://user-images.githubusercontent.com/3107574/65775184-97ef3d00-e137-11e9-8f49-2d7048f41840.png)

### What happened?
That error doesn't make any sense. The file is there on the .xpi file and the manifest is good.
Also made debug of the extension on firefox and runs good.

### What did you expect to happen?
Upload with success.

### Anything else we should know?
I have uploaded dozens of Addons on Firefox AMO and this is the first time I see this.

EDIT: Nevermind. The Firefox debug is not case sensitive, but the Mozzila AMO is case sensitive: ie: eventpage.js is different of eventPage.js

(Please include screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
> EDIT: Nevermind. The Firefox debug is not case sensitive, but the Mozzila AMO is case sensitive: ie: eventpage.js is different of eventPage.js

Yeah, I think this might also be related to the operating system maybe, as things are loaded from the actual disk when you're in Firefox. Maybe @rpl can confirm.

So, unless I misunderstood things are actually working as expected here. Please do let me know if I'm wrong though.

**Comment by rpl** [comment]
> Yeah, I think this might also be related to the operating system maybe, as things are loaded from the actual disk when you're in Firefox. Maybe @rpl can confirm.

Yes, I confirm, that is the reason behind that unexpected behavior:

- when loading temporarily from a directory, because of the filesystem case-insensitivity Firefox may be able to load successfully a filename that is not in the real case
- when loading the extension from a zip file, as it happens for a user that install the extension from AMO or from a link to the xpi, the files have to be in the right case (because their are part of the zip file, and it is case sensitive)

The validation has to be strict as it is, otherwise an extension submitted may not work as expected for the users and the developer may miss to notice it.
