### ISSUE TITLE
Port firefox schema import to use zip files

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2955]
So, it seems that the mozilla-unified downloads are only available as zip and not as .tar.gz anymore.

That'll unblock #2935

**Comment by EnTeQuAk** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1596135 and https://bugzilla.mozilla.org/show_bug.cgi?id=1597094 for some explanation

**Comment by EnTeQuAk** [comment]
Currently running into a few problems with fixing the tests… I don't seem to understand the yazl library to zip files - https://github.com/mozilla/addons-linter/compare/2955-use-zip-for-schema-import#diff-f636bdc441ca6ca61aef66fd814e2198R1138-R1149 - that's what the documentation does, that's what everyone else does but the zip it produces is completely empty. All the addFile calls are executed properly - and I don't see what might be wrong.

cc @rpl, maybe you're seeing something stupid that I'm doing?

**Comment by rpl** [comment]
> Currently running into a few problems with fixing the tests… I don't seem to understand the yazl library to zip files - https://github.com/mozilla/addons-linter/compare/2955-use-zip-for-schema-import#diff-f636bdc441ca6ca61aef66fd814e2198R1138-R1149 - that's what the documentation does, that's what everyone else does but the zip it produces is completely empty. All the addFile calls are executed properly - and I don't see what might be wrong.
> 
> cc @rpl, maybe you're seeing something stupid that I'm doing?

I just spotted a typo:
- at [line 1130](https://github.com/mozilla/addons-linter/compare/2955-use-zip-for-schema-import#diff-f636bdc441ca6ca61aef66fd814e2198R1130) the test is creating a `yazl.ZipFile` instance named `zipfile`
- then [between line 1138 and line 1149](https://github.com/mozilla/addons-linter/compare/2955-use-zip-for-schema-import#diff-f636bdc441ca6ca61aef66fd814e2198R1138-R1149) the test creates another `yazl.ZipFile` instance named `archive`, the file are being added to the `zipfile` instance but we are waiting and expecting the instance named `archive` to contains the added files

It should be enough to remove the `zipfile` instance and change the `files.forEach` callback to add call `archive.addFile(...)` instead of `zipfile.addFile(...)`, and that should make the `archive`'s generated zip file to contains the expected entries.

@cgrebs let me know if that actually helped, if it didn't I'm happy to come back and give it a try locally.

**Comment by EnTeQuAk** [comment]
:man_facepalming: that actually fixed the test - or at least the problem I had and made me progress a lot. Thanks a ton! I'll have a full PR for this some time on Monday now. Guess having a second pair of :eyes: always helps

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
Please add some STR for qa. Thanks!
