### ISSUE TITLE
Provide patch upstream to enable Eslint to enable tolerant mode in espree.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#316]
See also #314 for related info.

**Comment by tofumatt** [comment]
Eslint issue is here: https://github.com/eslint/eslint/issues/3815, just for ease-of-tracking.

**Comment by andymckay** [comment]
Supports #33

**Comment by muffinresearch** [comment]
I've looked into this. Eslint has recently moved to using Acorn with espree as just a wrapper as opposed to espree being an esprima fork. The problem is acorn didn't have an equivalent to the tolerant mode in esprima. It's in the process of being added but it might be a bit longer before a tolerant mode appears back in the new espree that works with eslint 2.x.

**Comment by tofumatt** [comment]
Re-evaluating this: @magopian said a lot of current add-ons are using this, but because we only care about WebExtensions (which will be new or ports from Chrome), it's not unreasonable to simply say "even though this _would_ work in Firefox we don't accept this code in a Web Extension", right?

I think we should actually close this and not implement it, forcing add-on devs writing WebExt to just do it the right way.

Not sure of anything else we'd want tolerant mode for, so if there is we shouldn't close.

**Comment by andymckay** [comment]
It's not unreasonable until we find a pile of people that use it, then we might revisit it.  I think the "lots of add-ons use it" comment comes from boiler plate code in the SDK from cfx.

**Comment by tofumatt** [comment]
Alrighty, closed as won't fix then!
