### ISSUE TITLE
File incorrectly recognized as minified

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#3160]
The file https://code.addons.mozilla.org/en-US/browse/2640660/versions/5019997/?path=data%2Finit.js is incorrectly recognized as minified, leading to truncation of it in the code-manager.

/cc @bobsilverberg

**Comment by wagnerand** [comment]
Another example: https://code.addons.mozilla.org/en-US/browse/2682840/versions/5167706/?path=Misc%2FScriptsExecuter.js

**Comment by wagnerand** [comment]
Counter example: https://code.addons.mozilla.org/en-US/browse/839191/versions/2153097/?path=hosts.js

This file completely breaks code-manager, assumingly because it's *not* recognized as being minimized.

**Comment by willdurand** [comment]
I don't think we can do anything about that, there will always be something wrongly detected and the current implementation isn't too bad. Given that code-manager allows to collapse or expand the content of a file, I am going to close this issue because reviewers can still see the full content of files.
