### ISSUE TITLE
Warn on filenames that start with _

### ISSUE THREAD

**Issue by bmwalters** [mozilla/addons-linter#3269]
### Note
I started to fix this in my fork here: https://github.com/bmwalters/addons-linter/tree/warning/chromium-illegal-filename but realized that the current scanner architecture only seems to check filenames and not directory names.

### Background
Chromium-based browsers forbid installing extensions that contain files or directories whose names begin with `_`.

Attempting to install an extension with these paths gives the following error:
```
Cannot load extension with file or directory name _foo. Filenames starting with "_" are reserved for use by the system.
Could not load manifest.
```

There are two exceptions to this rule: `_locales` and `_platform_specific`.

Here is how this check is implemented in Chromium: https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/file_util.cc;l=360-391;drc=a2e94b75b5a575c1e5838658e331744cad588b12

### Suggestion
addons-linter should scan for these paths and warn the developer that they are not compatible with Chromium-based browsers.

### Caveats
This will result in validation failures for extensions downloaded from the Chrome Web Store, since the store adds a directory named `_metadata` to uploaded extensions. I am unaware if AMO has similar behavior.

**Comment by Rob--W** [comment]
`_locales` is used in Firefox too (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization).
We don't care about `_platform_specific`, as it is obviously legacy technology in Chrome (https://developer.chrome.com/native-client/devguide/distributing).
`_metadata` doesn't have a special meaning on AMO,, so it doesn't need to be blocked. If anything, I would like to put `_metadata` in `RESERVED_FILENAMES` so that the generated error would be `RESERVED_FILENAME`.

Since files with underscores at the front aren't anything special, we see no point in adding a check to the linter.

**Comment by bmwalters** [comment]
Those descriptions make sense, although I still think this linter warning would be useful for developers who are creating portable webextensions but primarily developing in Firefox.

I personally encountered this issue when placing content scripts in a folder that started with an underscore (not any of the three names that have been discussed), which worked in Firefox but failed at install-time in Chrome.
