### ISSUE TITLE
Upcoming breaking changes from mdn-browser-compat-data

### ISSUE THREAD

**Issue by ddbeck** [mozilla/addons-linter#3323]
Hi, I'm a maintainer of [`mdn-browser-compat-data`](https://github.com/mdn/browser-compat-data) and [it was suggested](https://github.com/mdn/browser-compat-data/issues/6640#issuecomment-686629794) that I reach out to you about some upcoming breaking changes for the package, since you have the package as a dependency.

The summary is that we're planning to rename the package to `@mdn/browser-compat-data`. We've proposed a process to do this over the course of a few weeks in https://github.com/mdn/browser-compat-data/issues/6640. If you have any feedback or suggestions about this process, I'd appreciate it if you shared it in that issue. Thank you!

**Comment by rpl** [comment]
@ddbeck thanks for letting us know about this upcoming change, we'll monitor the upstream issue and replace the dependency on this repo when the first version has been published on npm,

**Comment by ddbeck** [comment]
A little update here: `@mdn/browser-compat-data` is now the preferred version and `mdn-browser-compat-data` is deprecated (which I think is what triggered the autoclosure of #3388). [Upgrade instructions are also available](https://github.com/mdn/browser-compat-data/blob/v1.1.0/UPGRADE-2.0.x.md). Please @-me if you run into any problems. Thank you!

**Comment by AlexandraMoga** [comment]
@wagnerand would some general regression testing (submitting various add-on types, triggering errors/warnings) suffice for these changes or is there something more specific we should focus on?

**Comment by wagnerand** [comment]
@AlexandraMoga That is a good question.

Ideally, if you have add-ons that are using APIs that recently changed (maybe @rpl could help identify some), you could submit those and verify that they are still producing the same output as before. And on the other hand, APIs that did not recently change should not trigger a validation message.

@rpl Thoughts?

**Comment by rpl** [comment]
> @AlexandraMoga That is a good question.
> 
> Ideally, if you have add-ons that are using APIs that recently changed (maybe @rpl could help identify some), you could submit those and verify that they are still producing the same output as before. And on the other hand, APIs that did not recently change should not trigger a validation message.
> 
> @rpl Thoughts?

@wagnerand @AlexandraMoga 

From a quick look to the [interdiff between the mdn/browser-compat-data version that we used before this change and the last released version](https://github.com/mdn/browser-compat-data/compare/v1.0.40...v2.0.3), it seems that there shouldn't be much that would affect our usage of that module, the only change related to the webextensions API is the one from mdn/browser-compat-data#6776

That change is related to the new options added to `browser.tabs.captureTab` from [Bug 1636508](https://bugzilla.mozilla.org/show_bug.cgi?id=1636508), but we are not currently using the mdn/browser-compat-data to verify the options (we do only check API methods compatibility) and so that change shouldn't actually make any difference for the current set of validation rules.

As additional notes that may be useful if we want to proceed with explicitly QA verify this change:

- we are only checking if the API methods are supported if the extension manifest does have an `applications.gecko.strict_min_version` property set to a particular min version, otherwise we don't check the browser-compat-data at all.

- as a QA verification we may do something like what Andreas does describe in his comment and run the old and new addons-linter on:

  - a small test extension (even a fake one just for the purpose of testing the linting results) that has a `applications.gecko.strict_min_version` set to `"57.0"` and calls the `browser.tabs.captureTab` method (e.g. just calling `browser.tabs.captureTab();` once in a background page script should be enough)
    - verify that we emit the two expected warnings (`INCOMPATIBLE_API` and `ANDROID_INCOMPATIBLE_API`) on the old new addons-linter version

As an additional smoke test we could also run lint a popular real extension (or a small sample of real extensions) and verify that we get the same results from both addons-linter version.

**Comment by AlexandraMoga** [comment]
I've noticed that a new linter version was published with https://github.com/mozilla/addons-linter/releases/tag/2.10.0 so I went ahead and verified the scenarios mentioned above on AMO -dev.

If an extension uses `browser.tabs.captureTab();` in combination with `"applications.gecko.strict_min_version": "57.0"`, both the new and the old linter versions will throw the following warnings:

![image](https://user-images.githubusercontent.com/31961530/97427491-4c502980-191d-11eb-8cc0-c44610e2aa35.png)

The validation warnings are not triggered when the `strict_min_version` is higher (`82.0` for example) or `"applications.gecko.strict_min_version:"` is not specified in the manifest. 

I've also compared some linting results for a few popular add-ons against the new and the old linter and the results were the same.
