### ISSUE TITLE
All errors unless totally fatal should add errors to the collector not throw.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#351]
This bug is to review that is the case and if not fix it.

Blocks #348

**Comment by EnTeQuAk** [comment]
@muffinresearch Just to verify that I understand the intention behind this, things like ``throw new Error('RDF Node is not defined');`` should not throw the exception but rather add the error-message to the collector and use a proper constant etc?

**Comment by tofumatt** [comment]
@EnTeQuAk That's correct; I don't think we have many places that throw rather than add to the collector, but if they do we'd need to change it.

**Comment by EnTeQuAk** [comment]
There are actually quite a few but compared to the overall amount of stuff it's not that many, yeah. I'll leave this open then though.

**Comment by jasmineflorencio** [comment]
@EnTeQuAk I'd also like to work on this issue since it blocks #348. How can I differentiate a fatal error from a non-fatal error? It looks like [this](https://github.com/mozilla/addons-linter/blob/master/src/linter.js#L75) is a fatal error but it's getting added to the collector. From your earlier comment it looks like the non-fatal errors are located in the installrdf.js and firefox-schemas-import.js files. Are there other files that have non-fatal errors?

**Comment by EnTeQuAk** [comment]
I falsely marked this as a good-first-bug which this isn't since it's obsolete. More explanation in https://github.com/mozilla/addons-linter/pull/1580#issuecomment-336077770
