### ISSUE TITLE
Add to MANIFEST_HOST_PERMISSIONS/MANIFEST_BAD_HOST_PERMISSION rules a link to MDN doc page as part of the description 

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#3893]
As part of #3891 we are going to add two new rule codes:
- MANIFEST_HOST_PERMISSIONS
- MANIFEST_BAD_HOST_PERMISSIONS

These two new rules are both related to the `host_permissions` manifest key, which is part of the new manifest_version 3 additions.

We don't have an MDN doc page related to `host_permissions` yet, once we have created it we should add a link to the new MDN reference page as part of the description of these two new linting rules.

**Comment by AlexandraMoga** [comment]
I've verified the `host_permissions` warnings and errors in MV3 and these are the results:

- invalid `host_permissions` value => the warning message contains a link pointing to the [MDN doc for host_permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions):
![image](https://user-images.githubusercontent.com/31961530/200564358-18cfd8cf-6814-4ba6-940e-935d6d26fdd8.png)

-  `host_permissions` not an array => the error message contains a link pointing to the [MDN doc for general manifest.json properties](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json):
![image](https://user-images.githubusercontent.com/31961530/200564880-92dc4657-228f-44e2-9468-e04e60fa6f8e.png)

@willdurand for the second example, shouldn't the link point to the host_permissions doc as well, instead of the general manifest.json doc?

**Comment by willdurand** [comment]
> @willdurand for the second example, shouldn't the link point to the host_permissions doc as well, instead of the general manifest.json doc?

No, this is a generic error about the data type so that's why it is a link to the manifest.json page (we reuse this error for all generic errors about manifest properties)
