### ISSUE TITLE
Replace `relaxed-json` with `strip-json-comments`

### ISSUE THREAD

**Issue by fregante** [mozilla/addons-linter#3910]
The [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json) mentions that:

> [manifest.json] is a JSON-formatted file, with one exception: it is allowed to contain "//"-style comments.

But RJSON is a bit more than that: https://github.com/phadej/relaxed-json#relaxed-json

Given this and that `relaxed-json` has [a few CLI-related dependencies](https://npmgraph.js.org/?q=relaxed-json@1.0.3), I'd suggest swapping it out for the more appropriate [strip-json-comments](https://github.com/sindresorhus/strip-json-comments), which has no dependencies.

Related:

- https://github.com/mozilla/addons-linter/issues/3601

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-19)

**Comment by fregante** [comment]
In general, I'm a bit confused about this file:

https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/src/parsers/json.js#L30

Why is esprima being used before RJSON at all? It seems that the whole `.parse` method should just be a plain call to `parse: json => JSON.parse(stripJsonComments(json))`

**Comment by fregante** [comment]
Side note: both `espree` and `esprima` are used in this project, so `esprima` should probably be dropped anyway (because eslint still loads `espree` )

**Comment by Rob--W** [comment]
RelaxedJSON is not used for parsing, but only as an attempt to get useful error messages. We can use `JSON.parse`, and if that fails, strip the comments and retry, and if that fails, try to extract a useful message from the original error (with line numbers for example).

For manifest.json and `_locales/<locale>/messages.json`, replacing the overly broad RJSON with stripJsonComments+JSON.parse should be safe, because Firefox itself already strips comments (without allowing a broader format): https://searchfox.org/mozilla-central/rev/4d90ff4537330d6b17cb956c0fadf759086d9bb7/toolkit/components/extensions/Extension.jsm#268-281

The linter also lints arbitrary JSON files:
- JSONParser uses RelaxedJSON: https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/src/parsers/json.js#L6
https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/src/parsers/json.js#L26
- used here: https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/src/scanners/json.js#L30
- referenced here: https://github.com/mozilla/addons-linter/blob/47c3a119f05957705bc9107f6bd8c0841260803e/src/linter.js#L353-L354

Perhaps we can disable JSON parsing for non-standard JSON files (i.e. not used by the extension framework in a special way). That would also resolve #3680

**Comment by fregante** [comment]
So I suggest replacing esprima and RJSON in favor of a combination of:

- strip-json-comments
- json-parse-even-better-errors

They're both light, dependency-free and more focused, whereas the other two:

- https://packagephobia.com/result?p=rjson
- https://packagephobia.com/result?p=esprima

**Comment by fregante** [comment]
So it turns out this is really simple:

```js
export const RJSON = {
  parse(jsonString) {
    return JSON.parse(stripJsonComments(jsonString));
  },
};
```

That's all that's needed… except that RJSON can detect duplicate keys and addons-linter specifically tests for them.

I don't know of a way to detect duplicate keys other than by parsing the JSON file manually (e.g via something like relaxed-json). I also tried `JSON.parse`'s reviver function but that also skips the duplicates.

Either the duplicate detection is dropped, or we cannot drop relaxed-json :(

The unfortunate part is that [relaxed-json](https://github.com/phadej/relaxed-json) hasn't seen updates in 5 years and it has a few heavy old deps
