### ISSUE TITLE
"/developer" is an invalid additional property

### ISSUE THREAD

**Issue by rimas-kudelis** [mozilla/addons-linter#3971]
### Describe the problem and steps to reproduce it:

I tried updating my dictionary extension on AMO. Since it's the first time I have to package it with manifest.json instead of addons.rdf, I'm creating the manifest as I go.

Reading the [manifest documentation on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json), I noticed that there are two ways to specify the addon author: either by using "author" and/or "homepage_url" keys, or by using "developer/name" and "developer/url" keys. Since the latter method takes precedence if both methods are used, I assumed it's the preferred way and added the "developer" key to my manifest json. However, upon uploading the extension to AMO, I was presented with the following error message:

> "/developer" is an invalid additional property

### What happened?
An error message about an unsupported property was returned.

### What did you expect to happen?
No error message should have been returned.

### Anything else we should know?
No, nothing.

**Comment by willdurand** [comment]
Ok, thanks!

**Comment by rimas-kudelis** [comment]
Will there be an explanation why this is simply being closed?

**Comment by willdurand** [comment]
I am sorry: did I misread your last comment? I thought the problem was solved.

**Comment by rimas-kudelis** [comment]
I worked it around by specifying the developer differently (using `author` and `homepage_url` keys instead). It doesn't mean that the issue is void though, does it?

**Comment by willdurand** [comment]
oh, ok, that I didn't know. In which case, yeah I guess the issue is valid. It was still useful because I didn't know about the `developer ` attributes and I started to work on better supporting it: #4008

**Comment by rimas-kudelis** [comment]
Thank you!

It was mentioned in the original description though, maybe you skimmed through it too fast or something. :wink:

**Comment by willdurand** [comment]
Yeah, totally possible that I misinterpreted and moved on.

I can reproduce the bug and it is a tricky one: `/developer` is supported for extensions but the manifest above has a `dictionaries` top-level attribute, which I think makes it an add-on of type "dictionary" and not "extension". If we remove `"dictionaries": { ... }` in the manifest, the linter doesn't report any error.

In our JSON schema, we [define `/developer` in the `WebExtensionManifest` type](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas/manifest.json#287-302), which extends `ManifestBase`. Dictionaries are [defined by the `WebExtensionDictionaryManifest` type](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas/manifest.json#389-414), which also extends `ManifestBase`. In other words, the `/developer` attribute cannot be used for dictionaries and that is not a bug in the linter because FF does not support it either.

I am not too sure why `/developer` has been added to the `WebExtensionManifest` type. At the very least, the MDN pages could be updated a bit to mention when it is possible to use the different props.

**Comment by rimas-kudelis** [comment]
Wow, so that's how it is! I wonder why it's so complicated. I thought a dictionary is just a special (probably Mozilla-specific) type of extension. It seems to me that perhaps the `/developer` key was added to `WebExtensionManifest` and not `ManifestBase` by mistake?

**Comment by willdurand** [comment]
As mentioned above, this is a problem in Firefox. I filed a bug and attached a patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1739602. Thanks @rimas-kudelis for the report!

I am going to keep this issue opened until we import the new schema definitions.

**Comment by rimas-kudelis** [comment]
You probably meant to comment this on some other GitHub issue? Or reference some other Bugzilla issue? Because I looked at the patch attached there, and it doesn't seem to be about moving the definition of for `/developer` from `WebExtensionManifest` to `ManifestBase`.

**Comment by willdurand** [comment]
mmh I edited the message because I linked to the wrong bug before but it should be the right one now.

**Comment by rimas-kudelis** [comment]
Oh, indeed, the link is correct. I must've clicked it in the email and didn't consider that it could have been changed before commenting. Thanks!

**Comment by willdurand** [comment]
The Firefox patch has landed in m-c, the target release is 96. That essentially means we will be able to close this issue when we re-import the json schema in a few weeks.
