### ISSUE TITLE
Your add-on failed validation with 1 error "/manifest_version" should be <= 2

### ISSUE THREAD

**Issue by vir2alexport** [mozilla/addons-linter#4187]
Hi,

I use Firefox  97.0 (64-bit) and also tried the same on 96.0.3 (64-bit)

When do you expect new manifest version 3 come into play? It's already working on Chrome and Edge.

Regards.

![wtf-mozilla-firefox-manifest-v3](https://user-images.githubusercontent.com/25153080/153692823-b85d101e-1cd4-4b7b-b98a-db4db8e69ef9.jpg)

**Comment by vsromanc** [comment]
+1

**Comment by Keith-Hon** [comment]
I have the same issue today

**Comment by willdurand** [comment]
> I have the same issue today, is firefox addon not supporting v3 yet?

Nope, not yet.

**Comment by Keith-Hon** [comment]
> 

Okay, got it.

**Comment by willdurand** [comment]
I am going to close this issue for now since there is nothing "actionable" on the engineering side. We should come up with a more specific timeline in the future, I just don't know when exactly and that is beyond my work.

As a FF engineer working on the WebExtensions framework, I do know that we are working on a set of MV3 features intended for developers. AFAIK there should be some communication about it in May or so.
