### ISSUE TITLE
openDialog triggers addon-linter

### ISSUE THREAD

**Issue by leanderseige** [mozilla/addons-linter#4188]
### Describe the problem and steps to reproduce it:

I had a function called openDialog(null) in one of my React components. 

### What happened?

The addon-linter threw an error because it misunderstood it as window.openDialog().

### What did you expect to happen?

I expect addon-linter to not throw an error in this situation.

### Anything else we should know?

When submitting a new addon (https://addons.mozilla.org/de/developers/addon/submit/distribution) with this problem on the web, just a generic error message is displayed. 

I ran the linter on my local machine to find out what the error was:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/4111531/153776244-d1ffa302-7e45-4eb1-941a-b580e3f9ec65.png">

**Comment by willdurand** [comment]
I am wondering what `window.openDialog(null)` does given that the first argument is supposed to be a non-null string value.

**Comment by willdurand** [comment]
Oh wait, are you saying you have a method called `openDialog()` that isn't called on `window`?

**Comment by willdurand** [comment]
hmf, so we seem to have two rules for [`openDialog`](https://developer.mozilla.org/en-US/docs/Web/API/Window/openDialog) and none of them check that the method is bound to `window`. That does not look quite correct to me but that was probably implemented before my time so I'll need to dig a bit more. I believe we do this because it is easier (no need to find out if `whatever` corresponds to `window` in `whatever.openDialog("")` for instance).

The problem here is that the first argument should not be `null`. Given we throw a `TypeError`, we should probably handle this error in our code anyway because it is _still_ possible for an add-on to contain `window.openDialog(null)`, even if it is incorrect.

**Comment by leanderseige** [comment]
Yes, I had my own openDialog() which had nothing to do with Window.openDialog() at all and it was perfectly fine to call it with (null). In order to deal with the problem I renamed my function. But I think the linter should check whether the function is bound to window or not in order to avoid false alerts.

**Comment by willdurand** [comment]
> But I think the linter should check whether the function is bound to window or not in order to avoid false alerts.

Yeah, that I am not sure how hard it will be but we can avoid the `TypeError` at the very least. I submitted a PR for that. Now the question is whether we want to report a warning when we find `openDialog(null)`.

**Comment by ioanarusiczki** [comment]
@willdurand In case this can be tested by qa, please add some STR
Thanks!

**Comment by ioanarusiczki** [comment]
@willdurand 
Ok, so using something like `whatever.openDialog(null);` will be caught -> it triggers a yellow warning such as: 

![openDialog function](https://user-images.githubusercontent.com/33448286/154229006-d6a89836-e81e-4267-890a-ea4768c24733.png)

With an older linter version this scenario did not pass validation. 

I verified it with v 4.11.0 which is supported currently by AMO dev and AMO stage.
