### ISSUE TITLE
Add implementation/port percentage status to README

### ISSUE THREAD

**Issue by arieljannai** [mozilla/addons-linter#461]
It would be very comfortable and easy to understand the linter status that way. A percentage value or even a counter that says.

For example, the current status is something like (I've just searched in the [status page](http://mozilla.github.io/addons-linter/) for the occurrences):
- 45~ ported, 95~ removed, 50~ not yet ported
- 4 info, 23 notice, 132 warning, 49 error

So maybe have something automatic that will update it.
For my opinion, it gives much more information.

Thanks,
Ariel

**Comment by muffinresearch** [comment]
@arieljannai It's a good idea - however, right now the rules doc is incorrect since we're dropping support for old-style extensions in this linter (they will contine to be handled by the amo-validator) and we still need to remove the code + rules for those things that aren't relevant.

Once that's been cleaned up we can take a look at this.

**Comment by EnTeQuAk** [comment]
Given that we agreed that addons-linter will only focus on WebExtensions and maybe other things like langpacks or dictionaries - which seem to be supported for a longer time - I think adding a "porting status" will end up being confusing and not relevant. If we're adding stuff it'll be focused on WebExtensions and I'd say it's nothing that we can easily describe in a percentage-value.

I'm going to close this, in case I misunderstood that issue feel free to re-open anytime.
