### ISSUE TITLE
Tests fail with node 4

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#472]
With node `v4.2.3` I get a test failure. If switch back to the system node (which for me is 0.12.2) then tests pass as expected. Full log attached.
````
  1) Xpi.open() should resolve with zipfile:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
      at run (node_modules/core-js/modules/es6.promise.js:104:47)
      at node_modules/core-js/modules/es6.promise.js:115:28
      at flush (node_modules/core-js/modules/$.microtask.js:19:5)
````

[addons-linter-npm-test.txt](https://github.com/mozilla/addons-linter/files/113157/addons-linter-npm-test.txt)

**Comment by muffinresearch** [comment]
Yep I see the same thing. Going to add more node versions to Travis for the future.

Looking into the root cause...

**Comment by muffinresearch** [comment]
Seems to be related to the npm version. If you use npm 2.x it works 3.x it doesn't. I suspect there's something odd happening wrt deps.

**Comment by muffinresearch** [comment]
So further investigations show that tests *without* coverage are really fast, but tests with it are really slow. Seems with the newer node + npm combo we're tipping over the 5000ms limit on some tests. Upping the timeout limit seems to make it work, but this is more a workaround than addressing the root cause.

grunt clean test

real	0m24.723s
user	0m25.036s
sys	0m1.140s

grunt clean test-no-coverage (requires a patch to fix a problem with test-no-coverage).

real	0m12.553s
user	0m12.987s
sys	0m0.860s
