### ISSUE TITLE
Some corrections are needed for browser_specific_settings.gecko_android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-linter#4898]
Followup for https://github.com/mozilla/addons-server/issues/20530

While making the submission I checked both applications: 

1. With this [manifest.json ](https://code.addons-dev.allizom.org/en-US/browse/625526/versions/1699334/) where strict_min_version for Android was set below 113.0,  I don't have any [validation](https://addons-dev.allizom.org/en-US/developers/addon/android-gecko-1/file/419977/validation) warnings, and the [reviewer page ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625526) shows a Compatibility : Firefox for Android 113.0 and later 

This scenario should throw a warning that FF version for android is too low.

2. Another submission with this [manifest.json](https://code.addons-dev.allizom.org/en-US/browse/625528/versions/1699336/) will throw 2 warnings -> [validation result](https://addons-dev.allizom.org/en-US/developers/addon/android-gecko3/file/419979/validation) [Reviewer's page ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625528) shows 113.0 for Android and 90.0 for Firefox (as it was set in the manifest) 

This scenario should not throw any warnings

**Comment by ioanarusiczki** [comment]
Maybe for strict_min_version <130.0 ,the linter should throw an error and not warning.

**Comment by Rob--W** [comment]
@ioanarusiczki Could you paste the manifest.json files that you were using in the test along with the observed results?

I have been thinking here. On the one hand, since `gecko_android` wasn't recognized until 113, it could make sense to enforce a min value of 113.

On the other hand, since the value wasn't enforced earlier, it doesn't matter if the version is lower, at least in Firefox. But since the value is consumed by AMO, it would still make sense to accept lower values, so that extension developers can mark their extensions as intentionally supporting an earlier version.

**Comment by ioanarusiczki** [comment]
@Rob--W 
The first scenario: 

`{
  "manifest_version": 2,
  "version": "4.0",
  "description": "A test extension from webext-generator.",
  "name": "gecko android key",
  "browser_specific_settings": {
    "gecko": {
      "id": "testdummy222@testioana"
    },
    "gecko_android": {
      "strict_min_version": "90.0"
    }
  }
}`

The second: 

`{
  "manifest_version": 2,
  "version": "8.0",
  "description": "A test extension from webext-generator.",
  "name": "gecko android key",
  "browser_specific_settings": {
    "gecko": {
      "id": "testdummy111@testioana",
      "strict_min_version": "90.0"
    },
    "gecko_android": {
      "strict_min_version": "113.0"
    }
  }
}`

**Comment by diox** [comment]
> On the one hand, since gecko_android wasn't recognized until 113, it could make sense to enforce a min value of 113.

FWIW currently AMO silently records `113.0` in database if `browser_specific_settings.gecko_android.strict_min_version` was set to a lower version.

**Comment by willdurand** [comment]
@diox would you have time to look at this?

**Comment by diox** [comment]
1. For the first scenario, since AMO is silently correcting to `113.0` anyway (*), I think it would make more sense to warn or error directly from the linter here
2. For the second scenario it definitely looks like a linter bug we should fix.

(*) Starting today it will even bump the min even higher, because if the add-on isn't part of the limited set we currently allow for Fenix, the first acceptable version is going to be `119.0a1`.

**Comment by Rob--W** [comment]
> (*) Starting today it will even bump the min even higher, because if the add-on isn't part of the limited set we currently allow for Fenix, the first acceptable version is going to be `119.0a1`.

Would that prevent extensions from being installed on 118- even if the user is using the Collection override feature?

**Comment by diox** [comment]
Fenix doesn't look at AMO compatibility data when installing through the collection. There are even a couple add-ons in the official collection that aren't marked as compatible with Firefox for Android on AMO (I've notified @devaneymoz about it to get them fixed).

**Comment by diox** [comment]
So the bug here is that currently the linter makes compatibility checks with the `gecko.min_version` only, despite making those checks against both Firefox and Firefox for Android compatibility data. This results in weird results when using `gecko_android`, either alone or together with `gecko`.

The following scenarios need to be considered:
- `"gecko_android": {"strict_min_version": "113.0"}, "gecko": { "strict_min_version": "113.0"}`
- `"gecko_android": {"strict_min_version": "113.0"}, "gecko": { "strict_min_version": "57.0"}`
- `"gecko_android": {}, "gecko": { "strict_min_version": "57.0"}`
- `"gecko_android": {}`
- `"gecko_android": {"strict_min_version": "113.0}`

We need to agree on the expected results first. This will likely require quite a bit of refactoring to fix...

**Comment by ioanarusiczki** [comment]
@diox 

I tested all scenarios mentioned above and I've 2 questions: 

- for `"gecko_android": {}, "gecko": { "strict_min_version": "57.0"` or `"gecko_android": {"strict_min_version": "57.0}` this is the warning

![wrongwarning](https://github.com/mozilla/addons-linter/assets/33448286/c6ea388f-b277-47e1-9fa3-a40c62b08740)

I was expecting to warn it requires Firefox for Android 119.0a1 (which was released after 113.0 ) , so maybe the text needs to be modified ?

- when I'm submitting an addon that has in the manifest a strict_min:57.0 with strict_max:78.* the outcome in dev hub is a strict_min:119.0a1. Through API if I specify compatibility in the JSON the response returns strict_min:57.0 and strict_max:78*. 
It's a bit confusing, this might be expected but I can't remember.

**Comment by diox** [comment]
> I was expecting to warn it requires Firefox for Android 119.0a1 (which was released after 113.0 ) , so maybe the text needs to be modified ?

As far as the linter is concerned, [113.0 is correct](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#browser_compatibility). AMO enforces a minimum of 119.0a1 for Android if non-recommended at the moment, but the linter doesn't know that.

> when I'm submitting an addon that has in the manifest a strict_min:57.0 with strict_max:78.* the outcome in dev hub is a strict_min:119.0a1. 

Those values are invalid for `gecko_android` (it requires `113.0` and higher, as mentioned) so AMO ignores it. Behind the scenes AMO sets `113.0` min because you're using `gecko_android`, then realizes the add-on is not recommended for Android so it silently forces you to use `119.0a1`, and ignores your max completely.

> Through API if I specify compatibility in the JSON the response returns strict_min:57.0 and strict_max:78*.

It's confusing but expected: Without using `gecko_android` these values are valid.

**Comment by ioanarusiczki** [comment]
@diox 

Indeed, if I set a strict_min above 113.0 , I tried with 116.0 , it won't throw a warning and AMO will set it to 119.0a1. 

Thanks, I'm marking this verified.
