### ISSUE TITLE
Raise an error if there's another metadata-file if manifest.json exists

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#605]
We should throw an exception if there's a `install.rdf` or `package.json` once there's a `manifest.json` to make sure we block duplicated metadata early enough.

Tracking: https://github.com/mozilla/addons-server/issues/2450

**Comment by andymckay** [comment]
It actually already does this, the issues we are hitting right now on AMO are ones that are going through the amo-validator. We need to get the amo-linter working in prod so we can stop using the old one :)

I'll note that instead of raising a nice error, it throws an error. I'm going to change that.
