### ISSUE TITLE
Make CSS parse error clearer

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#623]
Currently comes out as "Unknown Word" mozilla/addons-server#2187

**Comment by muffinresearch** [comment]
@andym do you also see unknown word for a normal unparseable CSS file that's not in a `__MACOSX` directory? Right now the CSS parser will be handed resource forks in `__MACOSX` because they look like CSS (e.g. they end in `.css`) but that will soon be fixed by your patch in https://github.com/mozilla/addons-linter/pull/619

**Comment by andymckay** [comment]
Yes see this example: https://github.com/mozilla/addons-server/issues/2187#issuecomment-213169526

I think a CSS error should probably be lowered to a warning.

**Comment by muffinresearch** [comment]
OK I see that now - specifically with the example from https://github.com/mozilla/addons-server/issues/2187#issuecomment-208833429 (needs downloading and unpacking and then running of the .xpi).

A CSS syntax error means we can't parse the file any further, that should stay an error imho since we can't validate the file any further.

As for changing the error, I'm not sure what a better error would be in this case. The line is referenced and this is what the parser is telling us, that's not our error.

**Comment by andymckay** [comment]
@wagnerand should a failure in CSS parsing be an error that blocks add-on validation?

The problem is that showing "Unknown word" in the screenshot shown is completely unhelpful and we'll get a billion bugs about it.

**Comment by muffinresearch** [comment]
FWIW the actual error shown is `CSS_SYNTAX_ERROR` and it's the message that's 'Unknown word' (which comes from the parser):

<img src="https://cloud.githubusercontent.com/assets/1514/14993295/07363bd6-1162-11e6-8403-9b482ab995f8.png">

**Comment by andymckay** [comment]
![screenshot 2016-05-03 11 10 07](https://cloud.githubusercontent.com/assets/74699/14993446/b1aa2d36-111f-11e6-9090-c390530578ca.png)

Perhaps its a matter of saying "CSS: Unknown word"?

**Comment by wagnerand** [comment]
I don't think we should block validation (and therefore abort submission). We only do that if we are fairly sure the add-on won't work at all or is horribily breaks itself or Firefox.
A CSS syntax error does not necessarily mean the add-on is completely broken.

I would suggest making it a warning.
