### ISSUE TITLE
Multiplied warnings at webextension validation

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#707]
**Steps to reproduce:**
1. Try to submit the following webextension on AMO-dev or AMO-stage: 
[Puzzle-Creator.zip](https://github.com/mozilla/addons-linter/files/284264/Puzzle-Creator.zip)
2. Select “See full validation report”

**Expected results:**
A warning is displayed only a single time.

**Actual results:**
The same warning is specified for four times.

**Additional notes:**
- This issue reproduces on AMO-dev and AMO-stage using Firefox 49.0a1 (2016-05-25) under Windows 10 64-bit.
- Please see the attached screenshot for this issue:
![2016-05-26_1531](https://cloud.githubusercontent.com/assets/18114210/15574648/65f6d994-2357-11e6-82a0-32a9954b9ab2.png)

**Comment by andymckay** [comment]
This is actually perfectly accurate, in this add-ons case there are multiple uses of setTimeout on options.js on line 18, because its been compressed down into one line. The linter actually puts out that it occurs on options.js  line 18 column 4917, then line 18 column 5054.

I think maybe the real bug is surfacing the column number up into addons-server so it shows back to the developer.

**Comment by tofumatt** [comment]
Oddly I ran this on the latest linter locally and received a `TYPE_NOT_DETERMINED` error 😮

**Comment by andymckay-limited-access** [comment]
Make sure to run the validator on the .xpi inside the .zip.

**Comment by tofumatt** [comment]
Oops, I’m dumb!

**Comment by tofumatt** [comment]
Yup, filed https://github.com/mozilla/addons-server/issues/2769; the linter already outputs column number so closing this.
