### ISSUE TITLE
Scan all JSON files, not just manifest.json

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#779]
**Steps to reproduce:**
Submit the attached webextension:
[iCloud-Bookmarks_v1.4.20.zip](https://github.com/mozilla/addons-linter/files/331481/iCloud-Bookmarks_v1.4.20.zip)

**Expected results:**
A validation error appears explaining that a json file contains block comments and they  should be removed or replaced with “//”.

**Actual results:**
The webextension passes the validation without any error, but it cannot be installed because appears to be corrupted.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-23) under Windows 10 64-bit.
- After submitting and installing the webextension, several errors appear in Browser Console such as: 1466754498299	addons.webextension.<unknown>	ERROR	Loading extension 'null': Loading locale file _locales/nl/messages.json: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data     Log.jsm:753

**Comment by tofumatt** [comment]
Interesting, we don't scan other JSON files. Nice catch!

If you install a WebExtension with `//` comments in the locale JSON will it work in Firefox? Please let me know as it will influence our fix 😄

**Comment by vasilicamihasca** [comment]
The webextension is successfully installed in Firefox if I replaced all the block comments from locale JSON files with “//”. 
See the following example: https://addons-dev.allizom.org/en-US/firefox/addon/icloud-bookmarks2/

**Comment by tofumatt** [comment]
Awesome, thanks, should be an easy fix then. :)

- tofumatt

On 24 June 2016 at 10:24:00, vasilicamihasca (notifications@github.com)
wrote:

The webextension is successfully installed in Firefox if I replaced all the
block comments from locale JSON files with “//”.
See the following example:
https://addons-dev.allizom.org/en-US/firefox/addon/icloud-bookmarks2/

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/addons-linter/issues/779#issuecomment-228299513>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAFi92EdGxF0EJ03QFhLnJJ2B0lSo06qks5qO6IugaJpZM4I9lUX>
.

**Comment by tofumatt** [comment]
Turns out our JSON parsing is quite coupled to the Manifest JSON parser, and could be tidied up. This is more work than expected, but I think it's worth tackling.
