### ISSUE TITLE
Hybrid addon are rejected

### ISSUE THREAD

**Issue by ochameau** [mozilla/addons-linter#792]
In the following addon:
http://techno-barje.fr/public/browserui-addon-0.1.xpi
Sources over here:
https://github.com/ochameau/browserui
More info there:
http://blog.techno-barje.fr//post/2016/06/28/html-experiments/

I implement an hybrid addon, half bootstrapless, half WebExtension.
AMO validator rejects this addon with the following message:
    Both install_rdf and manifest.json found
    Unable to determine add-on type

I might be able to move the manifest.json to a sub-folder, would the linter be happy?

I totally understand this error, but that's unfortunate.

**Comment by andymckay** [comment]
You can't currently have both, because we have no way of figuring out if this is meant to be a webextension or not (this has caused an awful lot of bugs and problems). The hybrid add-on schema planned by @rpl allows for a webextension inside a folder called webextension, and the manifest would be in there. 

At this point this would be a won't fix, since this isn't a use case the linter or AMO supports.

If you do a hybrid add-on as per @rpl strategy, that would be validated as an SDK add-on.

**Comment by ochameau** [comment]
Thanks! It works perfectly with a webextension folder.

I would like to state that AMO is so much better these days. It has been years now since I uploaded an addon,
and the linter/validator looks actually helpful now rather than painful !!

**Comment by tofumatt** [comment]
Merci beaucoup ! We work hard on it so I'm glad you're finding it better! 😄
