### ISSUE TITLE
Warn about usage of iframes with remote src

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#813]
Remote iframes can be used to do bad things. Afer discussing the details with Kris, we agreed that the linter should warn reviewers when webextensions make use of them.

Reviewers should see a warning in the following cases:
- An iframe defined with no `src`. This usually means`src` is assigned programmatically. If we can detect that and only warn for remote `src`, even better.
- An iframe defined with a remote `src` and no `sandbox`.
- An iframe defined with a remote `src` and a `sandbox` attribute that has any values.

Reviewers should not see a warning in the following cases:
- An iframe defined with a remote `src` and a `sandbox` attribute that has no values.

**Comment by Rob--W** [comment]
@kmaglione 
What specific threats do you have in mind with remote frames?

I can't think of any case where remote frames with the sandbox attribute pose a smaller threat than a remote frame without a sandbox attribute.

The same-origin policy already protects against scripting access between the two documents.

The only potential issues I can think of is that once there was a vulnerability that allowed frames in extension pages to abuse the privileges of WebExtensions (CVE-2015-7223), and that the background page (and popup pages) can be navigated to a remote URL (https://bugzil.la/1286083 - this poses no security issues, but potentially privacy issues by having a remote frame with arbitrary content staying around forever). But Service Workers from the web platform already introduce this kind of privacy concerns, so that is not something specific to add-ons.

The only benefit that I see when warning about missing sandbox directives is that it forces add-on developers to really think about the capabilities that their frame needs. But given that there are already sufficient protections in place (Same origin policy), I think that this "benefit" does not outweigh the hassle or inpracticalities of warning about remote iframes without sandbox directive.

**Comment by wagnerand** [comment]
I pinged @cr about this a while ago. This is a friendly reminder and so she has a reference on where to reply :)

Thanks!

**Comment by pauljt** [comment]
I think it might be an interesting data point for reviewers, but I'm not sure think a warning is appropriate. I can imagine some risks, but I dont see 'sandbox' attribute mitigating anything in those cases.

You said you raised this based on discussions with @kmaglione  - if you can describe those in more detail maybe I can respond more intelligently. Specifically in what context (options pages? browser pages?) are you thinking about warning about? For the risks I can think of (loading remote content in privileged process, increased attack surface?)

**Comment by wagnerand** [comment]
We discussed the remaining questions on email. As of now, reviewers don't need to worry about remote iframes.
