### ISSUE TITLE
Provide a way to ignore node_modules and other artifacts

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#849]
When linting the source directory for an extension, it's typical to have some artifacts that won't actually make it into the final extension, like `node_modules`. The linter will likely die when scanning this dir so there should be a way to ignore them. The error I see is:

````
Error: ENFILE: file table overflow, open '/Users/kumar/tmp/blok/node_modules/nyc/node_modules/lodash/debounce.js'
    at Error (native)
````

I think the [Directory class](https://github.com/mozilla/addons-linter/blob/master/src/io/directory.js) just needs to accept some filtering.

I am mostly interested in providing programattic support for `web-ext lint`. See https://github.com/mozilla/web-ext/issues/397

**Comment by kumar303** [comment]
I can take a stab at this

**Comment by muffinresearch** [comment]
Just a thought; node does walk backwards looking for `node_modules`, I wonder if it might be better to tell people to move their node_modules above the extension dir?

Supporting them leaving node_modules in the directory increases the risk that they're accidentally packaged doesn't it or does web-ext automatically exclude them when it packages too?

Also, what happens if you're bundling some deps in an extension is it ok to use node_modules then or would the expectation be that you'd copy the lib?

**Comment by kumar303** [comment]
web-ext automatically excludes `node_modules`. I haven't seen anyone bundling their extension with webpack (or similar). That would probably require some additional build steps to point the manifest at the right source.

**Comment by pdehaan** [comment]
Not sure if relevant here, but in some projects (like min-vid) we ignore the node_modules directory, but in some cases want to pull in a specific npm module or files: https://github.com/meandavejustice/min-vid/blob/master/.jpmignore

Ideally we'd have a way of specifying files to add/ignore so the user can control which files can get added to their web-extension.

**Comment by kumar303** [comment]
We'd like to support an [ignore file](https://github.com/mozilla/web-ext/issues/131) in web-ext which could override the defaults. For the purpose of `web-ext lint`, this ignore file would apply to the linter as well.
