### ISSUE TITLE
Prevent use of * in strict_min_version

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#914]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1297752 its pointed out that usage of * in strict_min_version is confusing lots of people (48.* is not compatible with 48.0) and we should do our best to prevent this from happening until we come up with a better plan.

**Comment by ValentinaPC** [comment]
Verified this in AMO-dev FF48(Win 7 x64).
Results:
I was able to submit a webextension with strict_min_version value: "*" (as you can see in the attached screenshots)
![2016-09-02_0912](https://cloud.githubusercontent.com/assets/15685960/18194501/c2f69190-70ee-11e6-8441-6bc91cd3f4fa.png)
![steluta](https://cloud.githubusercontent.com/assets/15685960/18194502/c2f8afa2-70ee-11e6-9bb0-02397d865e13.png)

Also, it can be seen that the max_version is smaller than the min_version, and there is no problem returned at validation. (working as expected for add-ons)
![add-on](https://cloud.githubusercontent.com/assets/15685960/18194526/dbc80910-70ee-11e6-80af-524e97175b27.png)

Reopening.

**Comment by EnTeQuAk** [comment]
This didn't land on -dev yet, I just created a new release and will re-close this issue once the fix is on -dev.

**Comment by muffinresearch** [comment]
@EnTeQuAk when you have a sec it would be good to get the new version of the package landed in addons-server assuming no blockers at that end.

**Comment by EnTeQuAk** [comment]
doh! this ticket completely slipped through my todo lists, opened https://github.com/mozilla/addons-server/issues/3497 - it'll land next week unfortunately.

**Comment by EnTeQuAk** [comment]
This landed on -dev and will be on the list for the next deploy next week

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF48.0.2 (Win 7)
1. Tried with following values for strict_min_version: *, 48.*, null - and the next error message was displayed: 
![2016-09-16_1250](https://cloud.githubusercontent.com/assets/15685960/18582143/5c5c437a-7c0c-11e6-9186-f9c5f764360e.png)

2. Tried with following values for strict_min_version: 48.*b2, 48.0*, 48.*0, 48 - and the next error message was displayed:
![minmax](https://cloud.githubusercontent.com/assets/15685960/18582261/e1189bc2-7c0c-11e6-8ea1-643aaf1431b5.png)

@EnTeQuAk Is the message returned for the values enumerated at 2. correct? Thanks!

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48.0.2(Win 7) and obtained the following results: 

1. Values: `48.*b2`, `48.0*`, `48.*0`, `48`,` *.*` return "Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version? Invalid minimum version number" message.

2. Values: `*`, `48.*` return "/applications/gecko/strict_min_version" should match pattern "^[0-9]{1,3}(\.[a-z0-9]+)+$"

3. Strict_max_version accepts the value `"48.*"` as expected, but **returns an error** for max version like `"*"`. 

As far as I know, the restriction is applied only for min_version, or am I wrong? Because if I make a submission without adding min or max version, default range for max_version is `"*"`... then why do we not accept it in the first place?

**Comment by andymckay** [comment]
Thats probably a bug because I forgot about that, but I kinda wonder what the difference is between `"*"` and having no `strict_max_version` at all is. I can't think of one.

**Comment by ValentinaPC** [comment]
Maybe the author of the webextension, writes both `"strict_min_version"` and `"strict_max_version"` for consistency and is blocked for the wrong reason.
But, at the end, you are right, there is no difference. 

Let me know if you also want to cover the `"strict_max_version"` - `"*"` case, and I'll log another issue.
